const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const iconPaths={
 headphones:'<path d="M4 14v-2a8 8 0 0 1 16 0v2"/><path d="M18 19c0 1.1-.9 2-2 2h-1v-7h3c1.1 0 2 .9 2 2v3Z"/><path d="M6 19c0 1.1.9 2 2 2h1v-7H6c-1.1 0-2 .9-2 2v3Z"/>',
 speaker:'<rect x="5" y="3" width="14" height="18" rx="3"/><circle cx="12" cy="15" r="3"/><circle cx="12" cy="8" r="1.5"/>',
 tablet:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 18h6"/>',
 watch:'<rect x="7" y="6" width="10" height="12" rx="3"/><path d="M9 2h6l1 4H8l1-4Zm0 20h6l1-4H8l1 4Z"/><path d="M12 9v3l2 1"/>',
 battery:'<rect x="5" y="6" width="14" height="12" rx="2"/><path d="M19 10h2v4h-2M11 9l-2 4h3l-1 3 4-5h-3l1-2"/>',
 camera:'<path d="M5 7h3l1.5-2h5L16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="4"/>',
 wifi:'<path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M12 20h.01"/>',
 charger:'<path d="M9 2v6m6-6v6M7 8h10v3a5 5 0 0 1-5 5v6M8 22h8"/>',
 tv:'<rect x="3" y="5" width="18" height="13" rx="2"/><path d="m8 22 4-4 4 4"/>',
 cinema:'<rect x="3" y="6" width="18" height="14" rx="2"/><path d="M3 10h18M7 6l2 4m4-4 2 4m4-4 2 4"/>'
};
const families=[
 {name:'Auriculares',short:'Audio',icon:'headphones',color:'#7058f5'},{name:'Parlantes',short:'Parlantes',icon:'speaker',color:'#ff7a00'},{name:'Tablets',short:'Tablets',icon:'tablet',color:'#00a7b5'},{name:'Relojes y bandas',short:'Relojes',icon:'watch',color:'#df3b85'},{name:'Powerbanks',short:'Powerbanks',icon:'battery',color:'#5aa83b'},{name:'Cámaras',short:'Cámaras',icon:'camera',color:'#4a74e8'},{name:'Conectividad',short:'Conectividad',icon:'wifi',color:'#00a1d6'},{name:'Cargadores',short:'Cargadores',icon:'charger',color:'#edac00'},{name:'Televisores',short:'TV',icon:'tv',color:'#666a73'},{name:'Cinema home',short:'Cinema',icon:'cinema',color:'#c62828'}
];
const svgIcon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]}</svg>`;
let questions=[],state={},timerId=null,wheelRotation=0,sound=true,pendingBadge=null,pendingChallenge=null;
const screens=['homeScreen','playerScreen','gameScreen','endScreen','rankingScreen'];
function showScreen(id){screens.forEach(s=>$('#'+s).classList.toggle('active',s===id));}
function phase(id){['wheelPhase','questionPhase','resultPhase'].forEach(s=>$('#'+s).classList.toggle('active',s===id));}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function familyByName(name){return families.find(f=>f.name===name);}
function lighten(hex,alpha='22'){return hex+alpha;}
function beep(freq=440,d=.08,type='sine'){if(!sound)return;try{const AC=window.AudioContext||window.webkitAudioContext,c=new AC(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.055,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.start();o.stop(c.currentTime+d);}catch(e){}}
function saveProgress(){if(!state.name)return;localStorage.setItem('claroDesafioActive',JSON.stringify({...state,current:null,questionStarted:null}));$('#resumeBtn').classList.remove('hidden');}
function clearProgress(){localStorage.removeItem('claroDesafioActive');$('#resumeBtn').classList.add('hidden');}
function hasProgress(){try{const s=JSON.parse(localStorage.getItem('claroDesafioActive')||'null');return s&&s.name&&s.lives>0&&Object.keys(s.badges||{}).length<families.length;}catch{return false;}}
function initState(name,code){state={name,code,score:0,lives:3,streak:0,correct:0,total:0,badges:{},familyCorrect:{},challengeReady:{},used:[],history:[],current:null,start:Date.now(),pendingImmediateChallenge:null};families.forEach(f=>state.familyCorrect[f.name]=0);updateHud();renderBadges();saveProgress();}
function hydrateState(saved){state=saved;state.badges||={};state.familyCorrect||={};state.challengeReady||={};state.history||=[];state.used||=[];families.forEach(f=>{state.familyCorrect[f.name]??=0;});updateHud();renderBadges();}
function updateHud(){$('#hudPlayer').textContent=state.name||'—';$('#hudScore').textContent=(state.score||0).toLocaleString('es-AR');$('#hudStreak').textContent=state.streak||0;$('#hudLives').textContent='● '.repeat(Math.max(0,state.lives||0))+'○ '.repeat(Math.max(0,3-(state.lives||0)));}
function renderBadges(){const won=Object.keys(state.badges||{}).length;$('#badgeCounter').textContent=`${won}/10`;$('#badgesGrid').innerHTML=families.map(f=>{const isWon=!!state.badges?.[f.name],ready=!!state.challengeReady?.[f.name]&&!isWon,progress=Math.min(3,state.familyCorrect?.[f.name]||0);return `<div class="badge-item ${isWon?'won':ready?'ready':''}" style="--family:${f.color}"><div class="badge-icon">${svgIcon(f.icon)}</div><div class="badge-copy"><strong>${f.name}</strong><span>${isWon?'Conquistada':ready?'Desafío listo':'En progreso'}</span></div><b class="badge-status">${isWon?'✓':ready?'!':progress+'/3'}</b></div>`}).join('');}
function heroIcons(){const pos=[[8,20],[43,-5],[78,18],[84,61],[43,87],[5,62]];$('#heroIcons').innerHTML=families.slice(0,6).map((f,i)=>`<span class="hero-icon" style="left:${pos[i][0]}%;top:${pos[i][1]}%;--icon:${f.color}">${svgIcon(f.icon)}</span>`).join('');}
function drawWheel(){const c=$('#wheelCanvas'),ctx=c.getContext('2d'),cx=c.width/2,cy=c.height/2,r=338,step=Math.PI*2/families.length;ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.shadowColor='rgba(50,15,20,.16)';ctx.shadowBlur=22;families.forEach((f,i)=>{const a=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+step);ctx.closePath();const g=ctx.createRadialGradient(cx,cy,70,cx,cy,r);g.addColorStop(0,'#ffffff');g.addColorStop(.28,f.color+'d9');g.addColorStop(1,f.color);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.94)';ctx.lineWidth=5;ctx.stroke();ctx.save();const mid=a+step/2;const tx=cx+Math.cos(mid)*245,ty=cy+Math.sin(mid)*245;ctx.translate(tx,ty);ctx.rotate(mid+Math.PI/2);if(mid>Math.PI/2&&mid<Math.PI*1.5)ctx.rotate(Math.PI);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 19px Inter,system-ui';ctx.fillText(f.short,0,6);ctx.restore();});ctx.restore();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=15;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,106,0,Math.PI*2);ctx.fillStyle='#f6f6f8';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=12;ctx.stroke();}
function weightedFamilyIndex(){let candidates=families.map((f,i)=>{const won=!!state.badges[f.name],ready=!!state.challengeReady[f.name]&&!won,p=state.familyCorrect[f.name]||0;let weight=won?1:ready?7:Math.max(2,6-p);const last=state.history[state.history.length-1],prev=state.history[state.history.length-2];if(last===f.name&&prev===f.name)weight=0;else if(last===f.name)weight*=.42;return {i,weight};});let total=candidates.reduce((s,c)=>s+c.weight,0),roll=Math.random()*total;for(const c of candidates){roll-=c.weight;if(roll<=0)return c.i;}return candidates[candidates.length-1].i;}
function spin(){if($('#spinBtn').disabled)return;$('#spinBtn').disabled=true;beep(210,.12,'triangle');const idx=weightedFamilyIndex(),step=360/families.length,current=((wheelRotation%360)+360)%360,desired=(360-(idx*step+step/2))%360,delta=((desired-current+360)%360)+(360*6);wheelRotation+=delta;$('#wheelCanvas').style.transform=`rotate(${wheelRotation}deg)`;const selected=families[idx];$('#wheelHeading').textContent='La rueda está eligiendo…';setTimeout(()=>{$('#wheelHeading').textContent=`Tu familia: ${selected.name}`;state.history.push(selected.name);state.history=state.history.slice(-8);startFamilyTurn(selected.name);$('#spinBtn').disabled=false;},4700);}
function pickQuestion(fam,{expert=false}={}){let all=questions.filter(q=>q.family===fam&&(expert?q.difficulty==='Experto':true));if(!all.length)all=questions.filter(q=>q.family===fam);let pool=all.filter(q=>!state.used.includes(q.id));if(!pool.length){const ids=new Set(all.map(q=>q.id));state.used=state.used.filter(id=>!ids.has(id));pool=all;}return pool[Math.floor(Math.random()*pool.length)];}
function shuffledQuestion(q){const entries=q.options.map((text,index)=>({text,correct:index===q.answer}));for(let i=entries.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[entries[i],entries[j]]=[entries[j],entries[i]];}return {...q,displayOptions:entries.map(x=>x.text),displayAnswer:entries.findIndex(x=>x.correct)};}
function startFamilyTurn(fam){const won=!!state.badges[fam],ready=!!state.challengeReady[fam]&&!won;if(ready)startQuestion(fam,'challenge');else if(won)startQuestion(fam,'master');else startQuestion(fam,'regular');}
function startQuestion(fam,mode='regular'){const expert=mode!=='regular',q=shuffledQuestion(pickQuestion(fam,{expert}));state.current={...q,mode};state.used.push(q.id);state.total++;const fi=familyByName(fam),progress=Math.min(3,state.familyCorrect[fam]||0);document.documentElement.style.setProperty('--family',fi.color);document.documentElement.style.setProperty('--family-soft',lighten(fi.color,'18'));$('#questionFamilyIcon').innerHTML=svgIcon(fi.icon);$('#questionFamilyLabel').textContent=fam;$('#questionModeLabel').textContent=mode==='challenge'?'Desafío de insignia':mode==='master'?'Maestría · puntos x2':'Pregunta regular';$('#questionProgressLabel').textContent=state.badges[fam]?'Familia conquistada':state.challengeReady[fam]?'Desafío habilitado':`Progreso ${progress}/3`;$('#questionDifficulty').textContent=q.difficulty;$('#questionType').textContent=q.type;$('#questionText').textContent=q.question;$('#optionsGrid').innerHTML=q.displayOptions.map((o,i)=>`<button class="option-btn" data-i="${i}"><span>${'ABCD'[i]}</span>${escapeHtml(o)}</button>`).join('');$$('.option-btn').forEach(b=>b.onclick=()=>answer(+b.dataset.i));phase('questionPhase');startTimer();saveProgress();}
function startTimer(){clearInterval(timerId);let left=15,elapsed=0;$('#timerText').textContent=15;$('#timerBar').style.width='100%';timerId=setInterval(()=>{elapsed+=.1;left=Math.max(0,15-elapsed);$('#timerText').textContent=Math.ceil(left);$('#timerBar').style.width=(left/15*100)+'%';if(left<=0){clearInterval(timerId);answer(-1);}},100);state.questionStarted=Date.now();}
function answer(choice){if(!state.current)return;clearInterval(timerId);const q=state.current;state.current=null;const correct=choice===q.displayAnswer,mode=q.mode;let earned=0,badgeJustWon=false,challengeActivated=false;if(correct){const seconds=Math.max(0,15-(Date.now()-state.questionStarted)/1000);state.streak++;const multiplier=mode==='master'?2:1;earned=(100+Math.round(seconds*4)+Math.min(100,state.streak*10))*multiplier;state.score+=earned;state.correct++;if(mode==='challenge'){state.badges[q.family]=true;state.challengeReady[q.family]=false;state.score+=500;badgeJustWon=true;pendingBadge=q.family;}else if(mode==='regular'){state.familyCorrect[q.family]=Math.min(3,(state.familyCorrect[q.family]||0)+1);if(state.familyCorrect[q.family]>=3&&!state.badges[q.family]){state.challengeReady[q.family]=true;state.pendingImmediateChallenge=q.family;challengeActivated=true;}}beep(mode==='challenge'?860:680,.15,'triangle');}else{state.streak=0;state.lives--;beep(125,.22,'sawtooth');if(mode==='challenge')state.challengeReady[q.family]=true;}updateHud();renderBadges();saveProgress();const card=$('.result-card');card.classList.toggle('incorrect',!correct);card.classList.toggle('challenge-result',mode==='challenge');$('#resultIcon').textContent=correct?'✓':'×';$('#resultKicker').textContent=correct?(mode==='challenge'?'Desafío superado':'Respuesta correcta'):(choice===-1?'Se terminó el tiempo':mode==='challenge'?'El desafío sigue pendiente':'Respuesta incorrecta');$('#resultTitle').textContent=correct?(badgeJustWon?'¡Insignia conquistada!':challengeActivated?'¡Desafío habilitado!':'¡Muy bien!'):`La correcta era ${'ABCD'[q.displayAnswer]}`;$('#resultExplanation').textContent=q.explanation;$('#pointsEarned').textContent=correct?`${badgeJustWon?'+500 extra · ':''}+${earned} puntos`:'Sin puntos';$('#continueBtn').textContent=challengeActivated?'Jugar desafío ahora':'Continuar';pendingChallenge=challengeActivated?q.family:null;phase('resultPhase');if(badgeJustWon)setTimeout(()=>showCelebration(q.family),500);}
function showCelebration(fam){const f=familyByName(fam);document.documentElement.style.setProperty('--family',f.color);document.documentElement.style.setProperty('--family-soft',lighten(f.color,'22'));$('#celebrationBadge').innerHTML=svgIcon(f.icon);$('#celebrationTitle').textContent=f.name;$('#celebrationText').textContent='Superaste el desafío experto y sumaste esta insignia a tu colección.';const colors=['#d71920','#ffcc00','#7058f5','#00a7b5','#5aa83b','#ffffff'];$('#confetti').innerHTML=Array.from({length:65},(_,i)=>`<i style="--x:${Math.random()*100}%;--c:${colors[i%colors.length]};--d:${2.1+Math.random()*2}s;--r:${Math.random()*180}deg;--drift:${-120+Math.random()*240}px"></i>`).join('');$('#badgeCelebration').classList.add('active');$('#badgeCelebration').setAttribute('aria-hidden','false');}
function continueGame(){if(state.lives<=0||Object.keys(state.badges).length===families.length){endGame();return;}if(pendingChallenge){const fam=pendingChallenge;pendingChallenge=null;state.pendingImmediateChallenge=null;startQuestion(fam,'challenge');return;}phase('wheelPhase');$('#wheelHeading').textContent='Girás y la rueda decide';saveProgress();}
function closeCelebration(){if(!pendingBadge)return;pendingBadge=null;$('#badgeCelebration').classList.remove('active');$('#badgeCelebration').setAttribute('aria-hidden','true');if(state.lives<=0||Object.keys(state.badges).length===families.length)endGame();else{phase('wheelPhase');$('#wheelHeading').textContent='Girás y la rueda decide';saveProgress();}}
function endGame(){const accuracy=state.total?Math.round(state.correct/state.total*100):0;$('#endTitle').textContent=Object.keys(state.badges).length===families.length?'¡Conquistaste las diez familias!':'Te quedaste sin vidas';$('#endScore').textContent=state.score.toLocaleString('es-AR');$('#endCorrect').textContent=state.correct;$('#endBadges').textContent=Object.keys(state.badges).length;$('#endAccuracy').textContent=accuracy+'%';saveRanking(accuracy);clearProgress();showScreen('endScreen');}
function saveRanking(acc){const key='claroDesafioRanking',list=JSON.parse(localStorage.getItem(key)||'[]');list.push({name:state.name,code:state.code,score:state.score,correct:state.correct,badges:Object.keys(state.badges).length,accuracy:acc,date:new Date().toISOString()});list.sort((a,b)=>b.score-a.score);localStorage.setItem(key,JSON.stringify(list.slice(0,50)));}
function renderRanking(){const list=JSON.parse(localStorage.getItem('claroDesafioRanking')||'[]');$('#rankingList').innerHTML=list.length?list.map((r,i)=>`<div class="rank-row"><b>${i+1}</b><div><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml(r.code||'Sin identificador')} · ${r.badges} insignias · ${r.accuracy}%</small></div><b>${r.score.toLocaleString('es-AR')}</b></div>`).join(''):'<p>Todavía no hay partidas guardadas en este dispositivo.</p>';}
async function boot(){questions=await fetch('questions.json').then(r=>{if(!r.ok)throw new Error('No se pudo cargar questions.json');return r.json();});heroIcons();drawWheel();$('#resumeBtn').classList.toggle('hidden',!hasProgress());showScreen('homeScreen');}
$('#startBtn').onclick=()=>showScreen('playerScreen');$('#resumeBtn').onclick=()=>{const saved=JSON.parse(localStorage.getItem('claroDesafioActive'));hydrateState(saved);showScreen('gameScreen');phase('wheelPhase');};$('#rankingBtn').onclick=()=>{renderRanking();showScreen('rankingScreen')};$('#endRankingBtn').onclick=()=>{renderRanking();showScreen('rankingScreen')};$('#beginGameBtn').onclick=()=>{const name=$('#playerName').value.trim(),code=$('#playerCode').value.trim();if(name.length<3){$('#playerName').focus();return;}initState(name,code);showScreen('gameScreen');phase('wheelPhase');};$('#spinBtn').onclick=spin;$('#continueBtn').onclick=continueGame;$('#celebrationContinue').onclick=closeCelebration;$('#playAgainBtn').onclick=()=>showScreen('playerScreen');$$('[data-action="home"]').forEach(b=>b.onclick=()=>showScreen('homeScreen'));$('#rulesBtn').onclick=()=>$('#rulesDialog').showModal();$('#closeRules').onclick=()=>$('#rulesDialog').close();$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};boot().catch(err=>{document.body.innerHTML=`<main style="padding:40px;font-family:system-ui"><h1>No se pudo iniciar el juego</h1><p>${escapeHtml(err.message)}</p></main>`});
