const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const families=[
 {name:'Auriculares',icon:'🎧',color:'#7B61FF'},{name:'Parlantes',icon:'🔊',color:'#FF7A00'},{name:'Tablets',icon:'▣',color:'#00A7B5'},{name:'Relojes y bandas',icon:'⌚',color:'#E43F8D'},{name:'Powerbanks',icon:'🔋',color:'#5AAB38'},{name:'Cámaras',icon:'📷',color:'#4A74E8'},{name:'Conectividad',icon:'📶',color:'#00A1D6'},{name:'Cargadores',icon:'⚡',color:'#F4B400'},{name:'Televisores',icon:'📺',color:'#6C6F78'},{name:'Cinema home',icon:'🎬',color:'#C62828'}
];
let questions=[]; let state={}; let timerId=null; let wheelRotation=0; let sound=true;
const screens=['homeScreen','playerScreen','gameScreen','endScreen','rankingScreen'];
function showScreen(id){screens.forEach(s=>$('#'+s).classList.toggle('active',s===id));}
function phase(id){['wheelPhase','questionPhase','resultPhase'].forEach(s=>$('#'+s).classList.toggle('active',s===id));}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function beep(freq=440,d=.08){if(!sound)return; const AC=window.AudioContext||window.webkitAudioContext; const c=new AC(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.connect(g);g.connect(c.destination);g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.start();o.stop(c.currentTime+d);}
function initState(name,code){state={name,code,score:0,lives:3,streak:0,correct:0,total:0,badges:{},familyCorrect:{},used:[],current:null,start:Date.now()};families.forEach(f=>state.familyCorrect[f.name]=0);updateHud();renderBadges();}
function updateHud(){$('#hudPlayer').textContent=state.name||'—';$('#hudScore').textContent=state.score||0;$('#hudStreak').textContent=state.streak||0;$('#hudLives').textContent='❤️'.repeat(Math.max(0,state.lives||0))+'🖤'.repeat(Math.max(0,3-(state.lives||0)));}
function renderBadges(){$('#badgesGrid').innerHTML=families.map(f=>`<div class="badge-item ${state.badges?.[f.name]?'won':''}"><i>${f.icon}</i><span>${f.name}</span><b>${state.badges?.[f.name]?'✓':(state.familyCorrect?.[f.name]||0)+'/3'}</b></div>`).join('');}
function drawWheel(){const c=$('#wheelCanvas'),ctx=c.getContext('2d'),cx=c.width/2,cy=c.height/2,r=315,step=Math.PI*2/families.length;ctx.clearRect(0,0,c.width,c.height);families.forEach((f,i)=>{const a=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+step);ctx.closePath();const grad=ctx.createRadialGradient(cx,cy,40,cx,cy,r);grad.addColorStop(0,'#fff');grad.addColorStop(.23,f.color+'cc');grad.addColorStop(1,f.color);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=6;ctx.stroke();ctx.save();ctx.translate(cx,cy);ctx.rotate(a+step/2);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 45px system-ui';ctx.fillText(f.icon,225,15);ctx.font='800 19px system-ui';ctx.fillText(f.name.length>12?f.name.split(' ')[0]:f.name,220,48);ctx.restore();});ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=14;ctx.stroke();}
function spin(){if($('#spinBtn').disabled)return;$('#spinBtn').disabled=true;beep(220,.12);const idx=Math.floor(Math.random()*families.length),step=360/families.length;const target=360*6+(360-idx*step-step/2);wheelRotation+=target;$('#wheelCanvas').style.transform=`rotate(${wheelRotation}deg)`;setTimeout(()=>{startQuestion(families[idx].name);$('#spinBtn').disabled=false;},4900);}
function pickQuestion(fam){let pool=questions.filter(q=>q.family===fam&&!state.used.includes(q.id));if(!pool.length){state.used=state.used.filter(id=>!questions.some(q=>q.id===id&&q.family===fam));pool=questions.filter(q=>q.family===fam&&!state.used.includes(q.id));}return pool[Math.floor(Math.random()*pool.length)];}
function startQuestion(fam){const q=pickQuestion(fam);state.current=q;state.used.push(q.id);state.total++;const fi=families.find(f=>f.name===fam);$('#questionFamily').textContent=fi.icon+' '+fam;$('#questionFamily').style.background=fi.color+'22';$('#questionFamily').style.color=fi.color;$('#questionDifficulty').textContent=q.difficulty;$('#questionType').textContent=q.type;$('#questionText').textContent=q.question;$('#optionsGrid').innerHTML=q.options.map((o,i)=>`<button class="option-btn" data-i="${i}"><span>${'ABCD'[i]}</span>${escapeHtml(o)}</button>`).join('');$$('.option-btn').forEach(b=>b.onclick=()=>answer(+b.dataset.i));phase('questionPhase');startTimer();}
function startTimer(){clearInterval(timerId);let left=15,elapsed=0;$('#timerText').textContent=left;$('#timerBar').style.width='100%';timerId=setInterval(()=>{elapsed+=.1;left=Math.max(0,15-elapsed);$('#timerText').textContent=Math.ceil(left);$('#timerBar').style.width=(left/15*100)+'%';if(left<=0){clearInterval(timerId);answer(-1);}},100);state.questionStarted=Date.now();}
function answer(choice){if(!state.current)return;clearInterval(timerId);const q=state.current;state.current=null;const correct=choice===q.answer;let earned=0;if(correct){const seconds=Math.max(0,15-(Date.now()-state.questionStarted)/1000);state.streak++;earned=100+Math.round(seconds*4)+Math.min(100,state.streak*10);state.score+=earned;state.correct++;state.familyCorrect[q.family]++;if(state.familyCorrect[q.family]>=3)state.badges[q.family]=true;beep(680,.12);}else{state.streak=0;state.lives--;beep(130,.2);}updateHud();renderBadges();const card=$('.result-card');card.classList.toggle('incorrect',!correct);$('#resultIcon').textContent=correct?'✓':'×';$('#resultKicker').textContent=correct?'Respuesta correcta':choice===-1?'Se terminó el tiempo':'Respuesta incorrecta';$('#resultTitle').textContent=correct?'¡Muy bien!':`La correcta era ${'ABCD'[q.answer]}`;$('#resultExplanation').textContent=q.explanation;$('#pointsEarned').textContent=correct?`+${earned} puntos`:'Sin puntos';phase('resultPhase');}
function continueGame(){if(state.lives<=0||Object.keys(state.badges).length===families.length){endGame();return;}phase('wheelPhase');}
function endGame(){const accuracy=state.total?Math.round(state.correct/state.total*100):0;$('#endTitle').textContent=state.lives>0?'¡Conquistaste las diez familias!':'Te quedaste sin vidas';$('#endScore').textContent=state.score;$('#endCorrect').textContent=state.correct;$('#endBadges').textContent=Object.keys(state.badges).length;$('#endAccuracy').textContent=accuracy+'%';saveRanking(accuracy);showScreen('endScreen');}
function saveRanking(acc){const key='claroDesafioRanking';const list=JSON.parse(localStorage.getItem(key)||'[]');list.push({name:state.name,code:state.code,score:state.score,correct:state.correct,badges:Object.keys(state.badges).length,accuracy:acc,date:new Date().toISOString()});list.sort((a,b)=>b.score-a.score);localStorage.setItem(key,JSON.stringify(list.slice(0,50)));}
function renderRanking(){const list=JSON.parse(localStorage.getItem('claroDesafioRanking')||'[]');$('#rankingList').innerHTML=list.length?list.map((r,i)=>`<div class="rank-row"><b>${i+1}</b><div><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml(r.code||'Sin identificador')} · ${r.badges} insignias · ${r.accuracy}%</small></div><b>${r.score}</b></div>`).join(''):'<p>Todavía no hay partidas guardadas en este dispositivo.</p>';}
async function boot(){questions=await fetch('questions.json').then(r=>r.json());drawWheel();showScreen('homeScreen');}
$('#startBtn').onclick=()=>showScreen('playerScreen');$('#rankingBtn').onclick=()=>{renderRanking();showScreen('rankingScreen')};$('#endRankingBtn').onclick=()=>{renderRanking();showScreen('rankingScreen')};$('#beginGameBtn').onclick=()=>{const name=$('#playerName').value.trim(),code=$('#playerCode').value.trim();if(name.length<3){$('#playerName').focus();return;}initState(name,code);showScreen('gameScreen');phase('wheelPhase');};$('#spinBtn').onclick=spin;$('#continueBtn').onclick=continueGame;$('#playAgainBtn').onclick=()=>showScreen('playerScreen');$$('[data-action="home"]').forEach(b=>b.onclick=()=>showScreen('homeScreen'));$('#rulesBtn').onclick=()=>$('#rulesDialog').showModal();$('#closeRules').onclick=()=>$('#rulesDialog').close();$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};boot();
