const categories=[
 {id:'audio',name:'Audio premium',icon:'◖',color:'#ff6b63'}, {id:'tv',name:'TV',icon:'▣',color:'#5f86ff'},
 {id:'cinema',name:'Cinema home',icon:'▶',color:'#a66cff'}, {id:'tablets',name:'Tablets',icon:'▤',color:'#f3a83b'},
 {id:'cameras',name:'Cámaras',icon:'◉',color:'#42b883'}, {id:'network',name:'Conectividad',icon:'⌁',color:'#16a5ad'},
 {id:'wearables',name:'Relojes',icon:'◌',color:'#344d78'}, {id:'energy',name:'Energía',icon:'ϟ',color:'#ff8d4d'},
 {id:'speakers',name:'Parlantes',icon:'◍',color:'#7d5fff'}, {id:'headphones',name:'Auriculares',icon:'∩',color:'#e7438e'}
];
const questions=[
{id:1,cat:'cinema',diff:'Intermedio',type:'Producto real',visual:true,image:'https://tienda.claro.com.ar/staticContent/Claro/images/catalog/productos/200x310/7008013.webp',q:'¿Qué ventaja concreta diferencia al Proyector TCL A1 frente a un proyector básico?',a:['Google TV con Netflix certificado y ajuste automático de imagen','Batería integrada para usarlo todo el día sin enchufe','Resolución 4K nativa y 3000 lúmenes','Subwoofer inalámbrico incluido'],correct:0,exp:'El TCL A1 combina Full HD nativo, Google TV con Netflix certificado y funciones automáticas de enfoque, corrección trapezoidal y evitación de obstáculos.'},
{id:2,cat:'audio',diff:'Experto',type:'Caso de cliente',visual:true,image:'https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw44cf25bc/1_JBL_BOOMBOX_3_HERO_BLACK_33216_x2.png?sw=537&sfrm=png',q:'Un cliente busca máxima potencia para fiestas al aire libre y no quiere preocuparse por arena o agua. ¿Qué argumento define mejor al JBL Boombox 3?',a:['180 W, hasta 24 horas y resistencia IP67','60 W, 8 horas y resistencia a salpicaduras','Sonido 2.1 para TV con HDMI ARC','Diseño ultracompacto para mochila'],correct:0,exp:'El Boombox 3 apunta a potencia real, bajos profundos, batería prolongada y resistencia IP67 para exterior.'},
{id:3,cat:'tablets',diff:'Intermedio',type:'Producto real',visual:true,image:'https://tienda.claro.com.ar/staticContent/Claro/images/catalog/productos/200x310/7007881.webp',q:'¿Qué beneficio comercial es más fuerte en la Huawei MatePad SE 11 con lápiz?',a:['Incluye M-Pen Lite y suma cuatro altavoces para estudio y entretenimiento','Tiene pantalla PaperMatte de 144 Hz y teclado incluido','Permite usar Samsung DeX','Incluye conexión 5G y GPS profesional'],correct:0,exp:'La MatePad SE 11 incluye el lápiz M-Pen Lite, pantalla de 11 pulgadas, cuatro altavoces y funciones familiares.'},
{id:4,cat:'tablets',diff:'Inicial',type:'Identificación visual',visual:true,image:'https://tienda.claro.com.ar/staticContent/Claro/images/catalog/productos/200x310/7006208.webp',q:'Esta Samsung Galaxy Tab A9 es una buena recomendación para una familia que busca...',a:['Una primera tablet confiable, metálica y con almacenamiento expandible','Reemplazar una notebook profesional con lápiz incluido','Diseño gráfico con pantalla PaperMatte','Gaming competitivo a 144 Hz'],correct:0,exp:'La Tab A9 es una opción de entrada confiable para entretenimiento, tareas y uso familiar, con cuerpo metálico y microSD.'},
{id:5,cat:'tv',diff:'Experto',type:'Comparación',visual:false,q:'¿Cuál de estas afirmaciones evita una mala recomendación al comparar TV?',a:['QLED describe tecnología de color; 4K describe resolución','Todo QLED es automáticamente 4K','Crystal UHD es lo mismo que QLED','Full HD tiene más detalle que 4K'],correct:0,exp:'Tecnología de pantalla y resolución son conceptos distintos. Un TV puede ser QLED Full HD o LED 4K.'},
{id:6,cat:'cinema',diff:'Intermedio',type:'Venta consultiva',visual:false,q:'Un cliente dice “con el sonido del televisor me alcanza”. ¿Cuál es la mejor respuesta?',a:['La barra no reemplaza el TV: mejora diálogos, graves e impacto sin una instalación compleja','La barra solo sirve para escuchar música','Todos los televisores tienen mal sonido','Sin barra no puede usar aplicaciones'],correct:0,exp:'La respuesta debe enfocarse en el beneficio y no atacar la decisión del cliente: mejor claridad e impacto con una solución simple.'},
{id:7,cat:'network',diff:'Inicial',type:'Caso de cliente',visual:false,q:'El Wi-Fi funciona bien en el living, pero no llega a la habitación del fondo. ¿Qué solución corresponde primero?',a:['Ubicar un repetidor en un punto intermedio con buena señal','Poner el repetidor dentro de la habitación sin señal','Cambiar el cargador del celular','Usar la banda de 5 GHz desde más lejos'],correct:0,exp:'El repetidor necesita recibir una señal razonable para poder ampliarla. Debe ubicarse antes de la zona muerta.'},
{id:8,cat:'cameras',diff:'Intermedio',type:'Necesidad del cliente',visual:false,q:'Una persona quiere controlar a su mascota y hablarle desde el trabajo. ¿Qué debe priorizar?',a:['Audio bidireccional y cobertura móvil de la cámara','Sirena exterior únicamente','Grabación 4K sin micrófono','Conexión HDMI ARC'],correct:0,exp:'El audio bidireccional permite escuchar y hablar, mientras una cámara móvil reduce puntos ciegos.'},
{id:9,cat:'tv',diff:'Intermedio',type:'Caso de cliente',visual:false,q:'Antes de recomendar una TV de 65 pulgadas, ¿qué pregunta ordena mejor la venta?',a:['¿Dónde la vas a usar y a qué distancia te sentás?','¿Querés la más cara?','¿Preferís cualquier marca?','¿La vas a pagar hoy?'],correct:0,exp:'El ambiente, la distancia y el uso determinan si el tamaño y las prestaciones tienen sentido.'},
{id:10,cat:'audio',diff:'Experto',type:'Aplicación',visual:false,q:'¿Qué dato transforma una especificación de audio en un beneficio para el cliente?',a:['Explicar qué cambia en su uso: volumen, graves, autonomía o resistencia','Leer todos los números de la caja','Comparar solo por precio','Nombrar la tecnología sin explicar para qué sirve'],correct:0,exp:'La venta consultiva traduce especificaciones en situaciones concretas de uso.'},
{id:11,cat:'cameras',diff:'Experto',type:'Seguridad',visual:false,q:'¿Qué función reduce falsas alertas provocadas por movimiento de mascotas o ramas?',a:['Detección inteligente de personas','Mayor volumen de sirena','Más resolución sin análisis','Más longitud de cable'],correct:0,exp:'La clasificación inteligente ayuda a diferenciar personas de otros movimientos.'},
{id:12,cat:'tablets',diff:'Experto',type:'Caso de cliente',visual:false,q:'Una persona quiere reemplazar parcialmente una notebook para estudiar y trabajar. ¿Qué combinación pesa más?',a:['Teclado, lápiz, buena RAM y multitarea','Cámara principal con más megapíxeles','Pantalla pequeña y poca batería','Solo parlantes más fuertes'],correct:0,exp:'Productividad exige entrada cómoda, memoria suficiente y un sistema de multitarea útil.'},
{id:13,cat:'cinema',diff:'Inicial',type:'Concepto',visual:false,q:'¿Qué aporta principalmente un subwoofer a una barra de sonido?',a:['Graves más profundos e impacto','Mayor resolución de imagen','Más velocidad de Internet','Más aplicaciones en el televisor'],correct:0,exp:'El subwoofer reproduce bajas frecuencias con más profundidad que una barra compacta.'},
{id:14,cat:'network',diff:'Experto',type:'Comparación',visual:false,q:'¿Cuándo conviene más un sistema mesh que un repetidor sencillo?',a:['En un hogar grande, con varias zonas y muchos dispositivos','Cuando falta batería en el celular','Cuando el TV no tiene sonido','Cuando se usan auriculares con cable'],correct:0,exp:'Mesh coordina varios nodos y ofrece una cobertura más uniforme para espacios grandes.'},
{id:15,cat:'tv',diff:'Intermedio',type:'Venta cruzada',visual:false,q:'¿Qué producto completa mejor una venta de TV orientada a cine y fútbol?',a:['Una barra de sonido','Un cargador de 20 W','Una smartband','Una cámara interior'],correct:0,exp:'La barra completa la experiencia audiovisual al mejorar voces, graves y amplitud.'},
{id:16,cat:'headphones',diff:'Intermedio',type:'Necesidad del cliente',visual:false,q:'Un cliente viaja todos los días y quiere escuchar sin subir demasiado el volumen. ¿Qué debería priorizar?',a:['Cancelación activa de ruido','Luces RGB','Cable más largo','Mayor tamaño de estuche'],correct:0,exp:'La cancelación activa reduce ruido constante del entorno y mejora la escucha a menor volumen.'},
{id:17,cat:'energy',diff:'Intermedio',type:'Compatibilidad',visual:false,q:'Para aprovechar carga rápida, ¿qué debe ser compatible?',a:['Dispositivo, cargador y cable','Solo el cargador','Solo la batería','El color del cable'],correct:0,exp:'La carga rápida depende de que toda la cadena admita potencia y protocolo compatibles.'},
{id:18,cat:'speakers',diff:'Intermedio',type:'Comparación',visual:false,q:'Dos parlantes tienen la misma potencia, pero uno posee batería mayor. ¿Qué mejora principalmente?',a:['La autonomía','La resistencia al agua','La calidad del micrófono','La velocidad de Bluetooth'],correct:0,exp:'La capacidad de batería impacta sobre todo en el tiempo de reproducción.'},
{id:19,cat:'wearables',diff:'Intermedio',type:'Compatibilidad',visual:false,q:'Antes de recomendar un reloj inteligente, ¿qué se debe validar?',a:['Compatibilidad con el sistema operativo del celular','Resolución del televisor','Cantidad de enchufes del hogar','Marca del router'],correct:0,exp:'Algunas funciones dependen de Android, iOS o del ecosistema de una marca.'},
{id:20,cat:'headphones',diff:'Experto',type:'Gaming',visual:false,q:'¿Por qué una conexión inalámbrica de 2,4 GHz suele preferirse para gaming competitivo?',a:['Porque ofrece menor latencia que el Bluetooth común','Porque mejora la resistencia al agua','Porque agrega memoria interna','Porque siempre duplica la batería'],correct:0,exp:'La menor latencia reduce el desfase entre la acción y el sonido.'},
{id:21,cat:'audio',diff:'Intermedio',type:'Venta consultiva',visual:false,q:'¿Qué pregunta ayuda más a elegir entre un parlante compacto y uno de alta potencia?',a:['¿Dónde y para cuántas personas lo vas a usar?','¿Qué color de celular tenés?','¿Qué cámara usás?','¿Cuánto pesa tu cargador?'],correct:0,exp:'El espacio, la cantidad de personas y la portabilidad definen la potencia necesaria.'},
{id:22,cat:'cameras',diff:'Intermedio',type:'Exterior',visual:false,q:'¿Qué combinación es esencial para una cámara exterior?',a:['Resistencia al clima y visión nocturna','Pantalla táctil y stylus','Dolby Atmos y HDMI','Carga inalámbrica y NFC'],correct:0,exp:'Una cámara exterior debe tolerar el ambiente y captar imágenes con poca luz.'},
{id:23,cat:'tablets',diff:'Intermedio',type:'Pantalla',visual:false,q:'¿Qué ventaja tiene una pantalla de 120 Hz frente a una de 60 Hz?',a:['Movimientos y desplazamientos más fluidos','Más almacenamiento','Mayor resistencia al agua','Más potencia de carga'],correct:0,exp:'Una mayor tasa de refresco mejora la fluidez visual.'},
{id:24,cat:'cinema',diff:'Experto',type:'Proyección',visual:false,q:'Una imagen de proyector se ve lavada durante el día. ¿Qué conviene corregir primero?',a:['Reducir la luz ambiente o usar una pantalla adecuada','Cambiar el cable de carga','Agregar un repetidor','Subir el volumen'],correct:0,exp:'La luz ambiente reduce contraste y hace que la imagen pierda fuerza.'}
];
const state={mode:'short',name:'',score:0,streak:0,lives:3,badges:{},progress:{},used:[],powers:{fifty:false,time:false,swap:false,shield:false},current:null,remaining:20,timer:null,visualOnly:false,rotation:0,lastCats:[]};
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function init(){renderBadges();qsa('.mode-card').forEach(b=>b.onclick=()=>{qsa('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode});qs('#startBtn').onclick=start;qs('#spinBtn').onclick=spin;qs('#continueBtn').onclick=()=>showScreen('wheelScreen');qs('#visualModeBtn').onclick=()=>{state.visualOnly=!state.visualOnly;qs('#visualModeBtn').textContent=state.visualOnly?'Modo visual activo':'Probar preguntas visuales';toast(state.visualOnly?'Se priorizarán preguntas con imágenes':'Modo visual desactivado')};qs('#soundBtn').onclick=()=>toast('Sonido de demo: activado');qsa('.power-card').forEach(b=>b.onclick=()=>toast('Los comodines se usan durante una pregunta.'));}
function start(){const name=qs('#playerName').value.trim();if(!name)return toast('Ingresá tu nombre para empezar.');state.name=name;qs('#homeView').classList.remove('active');qs('#gameView').classList.add('active');qs('#playerLabel').textContent=name;qs('#avatar').textContent=name[0].toUpperCase();updateHud();}
function renderBadges(){const target=state.mode==='short'?5:10;qs('#badgeCount').textContent=`${Object.keys(state.badges).length}/${target}`;qs('#badgeRail').innerHTML=categories.slice(0,state.mode==='short'?5:10).map(c=>`<div class="badge ${state.badges[c.id]?'unlocked':''}"><span class="badge-icon" style="--badge-bg:${c.color}">${c.icon}</span><span><b>${c.name}</b><small>${state.badges[c.id]?'Conquistada':`${state.progress[c.id]||0}/2 aciertos`}</small></span><span class="badge-state">${state.badges[c.id]?'★':'○'}</span></div>`).join('');}
function spin(){const available=categories.filter(c=>state.mode==='full'||categories.indexOf(c)<5);let weighted=[];available.forEach(c=>{const weight=state.badges[c.id]?1:state.progress[c.id]?4:5;for(let i=0;i<weight;i++)weighted.push(c)});if(state.visualOnly){const visualCats=[...new Set(questions.filter(q=>q.visual).map(q=>q.cat))];weighted=weighted.filter(c=>visualCats.includes(c.id));}
 let cat=weighted[Math.floor(Math.random()*weighted.length)];if(state.lastCats.length>=2&&state.lastCats.at(-1)===cat.id&&state.lastCats.at(-2)===cat.id)cat=available.find(c=>c.id!==cat.id)||cat;state.lastCats.push(cat.id);state.lastCats=state.lastCats.slice(-2);const idx=categories.findIndex(c=>c.id===cat.id);const target=360-(idx*36+18);state.rotation+=1440+target-(state.rotation%360);qs('#wheel').style.transform=`rotate(${state.rotation}deg)`;qs('#spinBtn').disabled=true;setTimeout(()=>{selectQuestion(cat.id);qs('#spinBtn').disabled=false},4700);}
function selectQuestion(cat,swap=false){let pool=questions.filter(q=>q.cat===cat&&!state.used.includes(q.id));if(state.visualOnly||state.used.length<2)pool.sort((a,b)=>Number(b.visual)-Number(a.visual));if(!pool.length){state.used=state.used.filter(id=>!questions.some(q=>q.id===id&&q.cat===cat));pool=questions.filter(q=>q.cat===cat)}let q=pool[Math.floor(Math.random()*Math.min(pool.length, state.visualOnly?Math.max(1,pool.filter(x=>x.visual).length):pool.length))];if(state.visualOnly){const vp=pool.filter(x=>x.visual);if(vp.length)q=vp[Math.floor(Math.random()*vp.length)]}state.current={...q,answers:shuffle(q.a.map((text,i)=>({text,correct:i===q.correct})))};if(!swap)state.used.push(q.id);renderQuestion();}
function renderQuestion(){clearInterval(state.timer);const q=state.current,c=categories.find(x=>x.id===q.cat);qs('#categoryPill').textContent=c.name;qs('#categoryPill').style.background=`${c.color}18`;qs('#categoryPill').style.color=c.color;qs('#difficultyPill').textContent=q.diff;qs('#questionType').textContent=q.type;qs('#questionText').textContent=q.q;const media=qs('#mediaPanel');media.style.display=q.visual?'grid':'none';if(q.visual){const img=qs('#productImage');img.src=q.image;img.onerror=()=>{img.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="560" height="420"><rect width="100%" height="100%" fill="#eef3f8"/><text x="50%" y="48%" text-anchor="middle" font-family="Arial" font-weight="700" font-size="24" fill="#53647a">Imagen no disponible</text><text x="50%" y="57%" text-anchor="middle" font-family="Arial" font-size="16" fill="#7b8998">La pregunta sigue siendo válida</text></svg>`)};}
 qs('#answers').innerHTML=q.answers.map((a,i)=>`<button class="answer-btn" data-i="${i}"><span class="answer-letter">${'ABCD'[i]}</span><span>${a.text}</span></button>`).join('');qsa('.answer-btn').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));renderQuestionPowers();state.remaining=20;updateTimer();state.timer=setInterval(()=>{state.remaining--;updateTimer();if(state.remaining<=0){clearInterval(state.timer);answer(-1)}},1000);showScreen('questionScreen');}
function renderQuestionPowers(){qs('#questionPowers').innerHTML=[['fifty','½ 50/50'],['time','+10 segundos'],['swap','↻ Cambiar'],['shield','◇ Escudo']].map(([k,l])=>`<button data-p="${k}" ${state.powers[k]?'disabled':''}>${l}</button>`).join('');qsa('#questionPowers button').forEach(b=>b.onclick=()=>usePower(b.dataset.p));}
function usePower(p){if(state.powers[p])return;state.powers[p]=true;if(p==='fifty'){const wrong=qsa('.answer-btn').filter((b,i)=>!state.current.answers[i].correct);shuffle(wrong).slice(0,2).forEach(b=>b.classList.add('disabled'));toast('Se eliminaron dos opciones.')}if(p==='time'){state.remaining+=10;updateTimer();toast('Sumaste exactamente 10 segundos.')}if(p==='swap'){clearInterval(state.timer);selectQuestion(state.current.cat,true);toast('Pregunta cambiada.')}if(p==='shield')toast('Escudo activado para este error.');renderQuestionPowers();}
function answer(i){clearInterval(state.timer);const chosen=state.current.answers[i],ok=chosen?.correct===true;qsa('.answer-btn').forEach((b,idx)=>{if(state.current.answers[idx].correct)b.classList.add('correct');else if(idx===i)b.classList.add('wrong');b.disabled=true});setTimeout(()=>showResult(ok),650);}
function showResult(ok){const q=state.current;if(ok){state.streak++;const multiplier=1+Math.min(state.streak-1,4)*.2;const pts=Math.round((160+state.remaining*5)*multiplier);state.score+=pts;state.progress[q.cat]=(state.progress[q.cat]||0)+1;if(state.progress[q.cat]>=2&&!state.badges[q.cat]){state.badges[q.cat]=true;qs('#resultTitle').textContent='¡Insignia conquistada!';qs('#resultKicker').textContent='Categoría dominada';qs('#earnedPoints').textContent=`+${pts+400} puntos`;state.score+=400}else{qs('#resultTitle').textContent='Muy bien';qs('#resultKicker').textContent='Respuesta correcta';qs('#earnedPoints').textContent=`+${pts} puntos`}qs('#resultIcon').textContent='✓';qs('#resultIcon').style.background='#eaf8f0';qs('#resultIcon').style.color='#269a59'}else{state.streak=0;if(state.powers.shield){state.powers.shield=false;toast('El escudo protegió tu vida.')}else state.lives=Math.max(0,state.lives-1);qs('#resultTitle').textContent='La próxima sale';qs('#resultKicker').textContent='Respuesta incorrecta';qs('#earnedPoints').textContent='Revisá el argumento';qs('#resultIcon').textContent='×';qs('#resultIcon').style.background='#fff0ef';qs('#resultIcon').style.color='#d83b30'}qs('#resultExplanation').textContent=q.exp;updateHud();renderBadges();updateMission();showScreen('resultScreen');}
function updateHud(){qs('#score').textContent=state.score.toLocaleString('es-AR');qs('#streak').textContent=`×${Math.max(1,state.streak)}`;qs('#lives').textContent='♥ '.repeat(state.lives)+'♡ '.repeat(3-state.lives)}
function updateMission(){const pending=categories.find(c=>!state.badges[c.id]&&(state.mode==='full'||categories.indexOf(c)<5));if(!pending){qs('#missionText').textContent='Colección completa. Excelente desempeño.';qs('#missionBar').style.width='100%';return}const p=state.progress[pending.id]||0;qs('#missionText').textContent=`${pending.name}: ${2-p} acierto${2-p===1?'':'s'} para conquistarla.`;qs('#missionBar').style.width=`${p*50}%`}
function showScreen(id){qsa('.stage-screen').forEach(s=>s.classList.remove('active'));qs('#'+id).classList.add('active')}
function updateTimer(){qs('#timerText').textContent=state.remaining;qs('#timerBar').style.width=`${Math.min(100,state.remaining/20*100)}%`}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function toast(msg){const t=qs('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2400)}
init();
